### ISSUE TITLE
Null values are automatically removed

### ISSUE THREAD

**Issue by aliwaris0572** [nvinayshetty/DTOnator#23]
@nvinayshetty Thanks for the great plugin,

However, if I have certain properties with null values, it automatically removes them and generates the class without that property. Could you please generate null property as well with `Object` data type.

Please find the json below:
`{
  "Response": {
    "Type": "SUCCESS",
    "Message": null,
    "Data": {
      "UserDetails": [
        {
          "DesignationId": 123,
          "DesignationName": "Manager",
          "ManagerId": 2,
          "ManagerName": "Test User"
        }
      ]
    }
  }
}`

While generating pojo classes, it does not generate `Message` property.

**Comment by nvinayshetty** [comment]
@aliwaris0572 You are trying to be lazy with something which is already lazy!
We need to figure out a right way to get the things done,Here are the few things to consider
when a key doesn't have a value
1. Consider it as string or object which will generate the mapping, but in reality it's completely useless .
   If it is actually a required field he is forced to edit it otherwise  we end up parsing useless data and 
  allocating memory.
2. Don't accept input where value is null and force the user to specify full JSON, here if the user knows  the data type for that key  he might enter the value so the problem solved, if not he might end up removing keys from the tool and add it manually later in the code.
3. Let's assume that the value being null indicates the user doesn't really care for that field so remove it completely from the generation, this forces the user to add that key back when required without the tool doing extra useless work and developer missing it!

**Comment by aliwaris0572** [comment]
> You are trying to be lazy with something which is already lazy!

Agreed,..!! :) 
Although, its someone else's shit that I need to worry about... You are right on your part.
